# Generated by Django 3.1 on 2020-09-06 03:48

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'default_related_name': 'tag'},
        ),
        migrations.AlterModelManagers(
            name='cart',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='collection',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='customer',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='customershipment',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='discount',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='order',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='orderorderproduct',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='orderproduct',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='ordershipment',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='productattribute',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='productattributevalue',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='producttag',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='productvariant',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='productvariantvalue',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='tag',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='password',
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cart',
            name='create_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 6, 10, 47, 40), null=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='create_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 6, 10, 47, 40), null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='create_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 6, 10, 47, 40), null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=250, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='discount',
            name='create_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 6, 10, 47, 40), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='create_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 6, 10, 47, 40), null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='create_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 6, 10, 47, 40), null=True),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='create_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 6, 10, 47, 40), null=True),
        ),
        migrations.AlterField(
            model_name='productattributevalue',
            name='create_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 6, 10, 47, 40), null=True),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='create_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 6, 10, 47, 40), null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='create_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 6, 10, 47, 40), null=True),
        ),
    ]
