# Generated by Django 3.1 on 2020-09-06 05:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200906_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='create_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 6, 12, 32, 10), null=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='create_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 6, 12, 32, 10), null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='create_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 6, 12, 32, 10), null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Female', max_length=6),
        ),
        migrations.AlterField(
            model_name='customershipment',
            name='country',
            field=models.CharField(choices=[('Viet_Nam', 'Viet Nam')], default='Viet_Nam', max_length=30),
        ),
        migrations.AlterField(
            model_name='discount',
            name='create_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 6, 12, 32, 10), null=True),
        ),
        migrations.AlterField(
            model_name='discount',
            name='type',
            field=models.CharField(choices=[('Percent', 'Percent'), ('Price', 'Price'), ('Free_ship', 'Free Ship')], default='Percent', max_length=9),
        ),
        migrations.AlterField(
            model_name='order',
            name='create_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 6, 12, 32, 10), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('Not_pay', 'Not Pay'), ('Paying', 'Paying'), ('Paid', 'Paid')], default='Not_pay', max_length=7),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipment_status',
            field=models.CharField(choices=[('Not_ship', 'Not Ship'), ('Shipping', 'Shipping'), ('Shipped', 'Shipped')], default='Not_ship', max_length=8),
        ),
        migrations.AlterField(
            model_name='product',
            name='create_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 6, 12, 32, 10), null=True),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='create_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 6, 12, 32, 10), null=True),
        ),
        migrations.AlterField(
            model_name='productattributevalue',
            name='create_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 6, 12, 32, 10), null=True),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='create_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 6, 12, 32, 10), null=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='name',
            field=models.CharField(choices=[('Color', 'Color'), ('Size', 'Size'), ('Material', 'Material')], max_length=250),
        ),
        migrations.AlterField(
            model_name='tag',
            name='create_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 6, 12, 32, 10), null=True),
        ),
    ]
