# Generated by Django 3.1 on 2020-09-06 05:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200906_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='create_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 6, 12, 39, 8), null=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='create_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 6, 12, 39, 8), null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='create_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 6, 12, 39, 8), null=True),
        ),
        migrations.AlterField(
            model_name='customershipment',
            name='city',
            field=models.CharField(blank=True, choices=[('Ha_Noi', 'Ha Noi'), ('Ho_Chi_Chi_Minh', 'Ho Chi Minh'), ('Phu_Tho', 'Phu Tho')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='customershipment',
            name='country',
            field=models.CharField(blank=True, choices=[('Viet_Nam', 'Viet Nam')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='customershipment',
            name='district',
            field=models.CharField(blank=True, choices=[('Cau_Giay', 'Cau Giay'), ('Nam_Tu_Liem', 'Nam Tu Liem'), ('Bac_Tu_Liem', 'Bac Tu Liem')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='discount',
            name='create_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 6, 12, 39, 8), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='create_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 6, 12, 39, 8), null=True),
        ),
        migrations.AlterField(
            model_name='ordershipment',
            name='city',
            field=models.CharField(blank=True, choices=[('Ha_Noi', 'Ha Noi'), ('Ho_Chi_Chi_Minh', 'Ho Chi Minh'), ('Phu_Tho', 'Phu Tho')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='ordershipment',
            name='country',
            field=models.CharField(blank=True, choices=[('Viet_Nam', 'Viet Nam')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='ordershipment',
            name='district',
            field=models.CharField(blank=True, choices=[('Cau_Giay', 'Cau Giay'), ('Nam_Tu_Liem', 'Nam Tu Liem'), ('Bac_Tu_Liem', 'Bac Tu Liem')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='create_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 6, 12, 39, 8), null=True),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='create_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 6, 12, 39, 8), null=True),
        ),
        migrations.AlterField(
            model_name='productattributevalue',
            name='create_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 6, 12, 39, 8), null=True),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='create_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 6, 12, 39, 8), null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='create_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 6, 12, 39, 8), null=True),
        ),
    ]
