# Generated by Django 3.1 on 2020-09-06 05:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200906_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='create_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 6, 12, 44, 9), null=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='create_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 6, 12, 44, 9), null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='create_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 6, 12, 44, 9), null=True),
        ),
        migrations.AlterField(
            model_name='customershipment',
            name='city',
            field=models.CharField(blank=True, choices=[('Ha Noi', 'Ha Noi'), ('Ho Chi Minh', 'Ho Chi Minh'), ('Phu Tho', 'Phu Tho')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='customershipment',
            name='country',
            field=models.CharField(blank=True, choices=[('Viet Nam', 'Viet Nam')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='customershipment',
            name='district',
            field=models.CharField(blank=True, choices=[('Cau Giay', 'Cau Giay'), ('Nam Tu Liem', 'Nam Tu Liem'), ('Bac Tu Liem', 'Bac Tu Liem')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='discount',
            name='create_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 6, 12, 44, 9), null=True),
        ),
        migrations.AlterField(
            model_name='discount',
            name='type',
            field=models.CharField(choices=[('Percent', 'Percent'), ('Price', 'Price'), ('Free ship', 'Free Ship')], default='Percent', max_length=9),
        ),
        migrations.AlterField(
            model_name='order',
            name='create_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 6, 12, 44, 9), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('Not pay', 'Not Pay'), ('Paying', 'Paying'), ('Paid', 'Paid')], default='Not pay', max_length=7),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipment_status',
            field=models.CharField(choices=[('Not ship', 'Not Ship'), ('Shipping', 'Shipping'), ('Shipped', 'Shipped')], default='Not ship', max_length=8),
        ),
        migrations.AlterField(
            model_name='ordershipment',
            name='city',
            field=models.CharField(blank=True, choices=[('Ha Noi', 'Ha Noi'), ('Ho Chi Minh', 'Ho Chi Minh'), ('Phu Tho', 'Phu Tho')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='ordershipment',
            name='country',
            field=models.CharField(blank=True, choices=[('Viet Nam', 'Viet Nam')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='ordershipment',
            name='district',
            field=models.CharField(blank=True, choices=[('Cau Giay', 'Cau Giay'), ('Nam Tu Liem', 'Nam Tu Liem'), ('Bac Tu Liem', 'Bac Tu Liem')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='create_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 6, 12, 44, 9), null=True),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='create_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 6, 12, 44, 9), null=True),
        ),
        migrations.AlterField(
            model_name='productattributevalue',
            name='create_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 6, 12, 44, 9), null=True),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='create_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 6, 12, 44, 9), null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='create_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 6, 12, 44, 9), null=True),
        ),
    ]
