# Generated by Django 3.1 on 2020-09-06 07:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200906_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='create_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 6, 14, 35, 36), null=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='create_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 6, 14, 35, 36), null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='create_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 6, 14, 35, 36), null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='update_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='discount',
            name='create_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 6, 14, 35, 36), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='create_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 6, 14, 35, 36), null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='create_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 6, 14, 35, 36), null=True),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='create_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 6, 14, 35, 36), null=True),
        ),
        migrations.AlterField(
            model_name='productattributevalue',
            name='create_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 6, 14, 35, 36), null=True),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='create_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 6, 14, 35, 36), null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='create_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 6, 14, 35, 36), null=True),
        ),
    ]
