# Generated by Django 3.1 on 2020-09-08 01:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20200908_0849'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tag',
            field=models.ManyToManyField(related_name='product', through='app.ProductTag', to='app.Tag'),
        ),
        migrations.AlterField(
            model_name='account',
            name='create_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 8, 8, 50, 15), null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='create_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 8, 8, 50, 15), null=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='create_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 8, 8, 50, 15), null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='create_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 8, 8, 50, 15), null=True),
        ),
        migrations.AlterField(
            model_name='customershipment',
            name='create_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 8, 8, 50, 15), null=True),
        ),
        migrations.AlterField(
            model_name='discount',
            name='create_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 8, 8, 50, 15), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='create_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 8, 8, 50, 15), null=True),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='create_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 8, 8, 50, 15), null=True),
        ),
        migrations.AlterField(
            model_name='ordershipment',
            name='create_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 8, 8, 50, 15), null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='create_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 8, 8, 50, 15), null=True),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='create_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 8, 8, 50, 15), null=True),
        ),
        migrations.AlterField(
            model_name='productattributevalue',
            name='create_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 8, 8, 50, 15), null=True),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='create_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 8, 8, 50, 15), null=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='create_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 8, 8, 50, 15), null=True),
        ),
        migrations.AlterField(
            model_name='productvariantvalue',
            name='create_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 8, 8, 50, 15), null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='create_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 8, 8, 50, 15), null=True),
        ),
    ]
